.SILENT:
# If we define in the current directory a file named clean or mrproper, this
# will break this makefile as these target do not have any dependencies, the
# target will always be more recent and will never be evaluated. The PHONY
# directive avoids this issue.
.PHONY: clean mrproper

CC		= g++ -g
CFLAGS	= -W -Wall -march=x86-64 -mtune=generic -O2 -pipe -fPIC -I/usr/include/qt/QtCore -I/usr/include/qt/QtWidgets -I/usr/include/qt/ -I/usr/include -I.
LDFLAGS	= -I. -isystem /usr/include/qt -isystem /usr/include/qt/QtWidgets -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtCore -I/usr/lib/qt/mkspecs/linux-g++ -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread


all: vehicle manager server path_finder

# Instead of repeating dependencies over and over again, make does support the
# following shortcuts. These also allow to avoid burden when we want to change
# the destination name of executables/targets for example.
#$@ : Target name;
#$< : First dependency;
#$? : More recent dependencies than the target;
#$^ : All the dependencies;
#$* : All wildcard character, same as * but syntax interpreted by make
vehicle: vehicle.o vehicle_main.o vehicle_moc.o generic.o
	echo "[+] Creating vehicle executable"
	$(CC) $(CFLAGS) $(LDFLAGS) -o $@ $^

# For compilation, the gcc default is to take the source file and replace its
# extension by .o. Specifying -o is in this use case, unneeded.
vehicle.o: vehicle.cpp vehicle.h vehicle_ui.h generic.h common.h
	echo "[+] Building vehicle.o"
	$(CC) -c $(CFLAGS) -o $@ $<

# Usually .h files are not found as target in Makefiles but this header file is
# generated by Qt libraries, let make it manually.
vehicle_ui.h: vehicle.ui
	echo "[+] Building vehicle_ui.h"
	uic -o $@ $<

vehicle_main.o: vehicle_main.cpp generic.h common.h
	echo "[+] Building vehicle_main.o"
	$(CC) -c $(CFLAGS) -o $@ $<

vehicle_moc.o: vehicle_moc.cpp vehicle.h
	echo "[+] Building vehicle_moc.o"
	$(CC) -c $(CFLAGS) -o $@ $<

# Usually .cpp files are not found as target in Makefiles but this moc file is
# generated by Qt libraries, let make it manually.
vehicle_moc.cpp: vehicle.h
	echo "[+] Building vehicle_moc.cpp"
	moc -o $@ $<

manager: manager.o manager_main.o manager_moc.o generic.o
	echo "[+] Creating manager executable"
	$(CC) $(CFLAGS) $(LDFLAGS) -o $@ $^

manager.o: manager.cpp manager.h manager_ui.h generic.h path.h
	echo "[+] Building manager.o"
	$(CC) -c $(CFLAGS) -o $@ $<

manager_ui.h: manager.ui
	echo "[+] Building manager_ui.h"
	uic -o $@ $<

manager_main.o: manager_main.cpp manager.h
	echo "[+] Building manager_main.o"
	$(CC) -c $(CFLAGS) -o $@ $<

manager_moc.o: manager_moc.cpp
	echo "[+] Building manager_moc.o"
	$(CC) -c $(CFLAGS) -o $@ $<

manager_moc.cpp: manager.h
	echo "[+] Building manager_moc.cpp"
	moc -o $@ $<

generic.o: generic.cpp generic.h
	echo "[+] Building generic.o"
	$(CC) -c $(CFLAGS) $<

server: server.cpp generic.o generic.h common.h
	echo "[+] Creating server executable"
	$(CC) $(CFLAGS) -o $@ $^

path_finder: path_finder.cpp generic.o generic.h
	echo "[+] Creating path_finder executable"
	$(CC) $(CFLAGS) -o $@ $^

clean:
	rm -fv *.o

mrproper: clean
	rm -fv vehicle manager server path_finder *ui.h *moc.cpp
