######################################################################
# Automatically generated by qmake (2.01a) jeu. nov. 12 22:44:31 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
greaterThan(QT_MAJOR_VERSION, 4): QT += widgets



# Input
HEADERS += vehicule.h
FORMS += vehicule.ui
SOURCES += main.cpp vehicule.cpp
